mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:pk>/report/", views.ReportView.as_view(), name="report"),
    path("<int:pk>/submitted/", views.SubmitView.as_view(), name="submitted"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:question_id>/submitReport/", views.submitReport, name="submitReport"),

]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now();
        return now >= self.pub_date >= now - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Report(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    input = models.TextField()
    def __str__(self):
        return "ID: " + str(self.question_id) + " Name:" + self.name + " Input:" +self.input

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# from django.django.http.response import HttpResponseRedirect
from .models import Question, Choice, Report
from django import forms


# Create your views here.
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now())



class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
class ReportView(generic.DetailView):
    model = Question
    template_name = "polls/report.html"

class SubmitView(generic.DetailView):
    model = Question
    template_name = "polls/submitted.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        context['report_list'] = Report.objects.filter(question_id=question_id)
        return context

    def get_queryset(self):
        return Report.objects.all()
def submitReport(request, question_id):
    #template_name = "polls/report.html"
    #return HttpResponseRedirect(reverse("polls:submitted", args=(question_id,)))

    questionId = request.POST.get("question_id")

    #Get values from Post data
    question = get_object_or_404(Question, pk=question_id)
    name = request.POST.get("name")
    input = request.POST.get("input")
    if not name or not input:
        return render(request, "polls/report.html", {"question": question, "error_message": "Please fill out all fields"})
        #return HttpResponseRedirect(reverse("polls:submitted", args=(question_id,title)))

    else:
        report = Report.objects.create(question=question, name=name, input=input)
        report.save()
        return HttpResponseRedirect(reverse("polls:submitted", args=(question_id,)))



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {"question": question,
                                                     "error_message": "You didn't select a choice.",
                                                     },
                      )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/detail.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

<div class="container-fluid">
<form action = "{% url 'polls:vote' question.id %}" method ="post">
    {% csrf_token %}
    <fieldset>
        <div class="mt-4 p-5 bg-info text-black rounded text-center">
            <h1>
            {{ question.question_text }}
            </h1>
            <a class="text-black" href = "/polls/">Back to Home</a><br>
        </div>
        <div class="text-center">
            {% if error_message %}
            <p><strong>
                {{ error_message}} }}
            </strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br>
            {% endfor %}
        </div>
        </fieldset>
    <div class="text-center">
        <input type="submit" value="Vote" class="btn btn-primary">

        <a href = "/polls/{{ question.id }}/report/">Report Poll</a>
    </div>
    </form>

</div>
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Django Tutorial <br> Author: Kathleen O'Donovan</small>
    </div>
  </footer>

polls/templates/polls/index.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}


{% load static %}
<div class="container-fluid ">
<div class="mt-4 p-5 bg-primary text-white rounded text-center">
    <h1>---Polls---</h1>
</div>
{# <link rel="stylesheet" href="{% static 'polls/style.css' %}"> #}

    {% if latest_question_list %}
    <ul class="nav nav-pills bg-light">
        {% for question in latest_question_list %}
        <li class="nav-item"><a class="nav-link" href = "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
<img src = "{% static 'polls/images/background.png' %}" class="rounded" alt="space">
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Django Tutorial <br> Author: Kathleen O'Donovan</small>
    </div>
  </footer>

polls/templates/polls/report.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

<form action = "{% url 'polls:submitReport' question.id %}" method ="post" class="container-fluid">
    {% csrf_token %}
    <fieldset>
    <div class="mt-4 p-5 bg-info text-black rounded text-center">
            <h1>
            Reporting on poll for question {{ question.id }}
            </h1>
            <a class="text-black" href = "/polls/">Back to Home</a><br>
        </div>
        <div class="text-center">
            {% if error_message %}
            <p><strong>
                {{ error_message }}
            </strong></p>
            {% endif %}
            <label>Question ID: </label><br>
            <input readonly type="text" name="question_id" id="question_id" value="{{ question.id  }}"><br>
            <label>Please enter your name: </label><br>
            <input type="text" name="name" id="name" placeholder="name"><br>
            <label>Please enter your issue with the poll: </label><br>
            <input type="text" name="input" id="input" placeholder="input">
        </div>



    </fieldset>
<div class="text-center">
    <br><input type="submit" value="Submit" class="btn btn-primary">
    <a href = "/polls/{{ question.id }}/">Back</a>
</div>
</form>
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Django Tutorial <br> Author: Kathleen O'Donovan</small>
    </div>
  </footer>

polls/templates/polls/results.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}


<div class="mt-4 p-5 bg-info text-black rounded text-center">
            <h1>{{ question.question_text }}</h1>
            <a class="text-black" href = "/polls/">Back to Home</a><br>
        </div>


{# <ul> #}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Answer</th>
            <th>Votes</th>
        </tr>
    </thead>
{% for choice in question.choice_set.all %}
    <tr>
        <th>{{ choice.choice_text }}</th>
        <th>{{ choice.votes }} vote{{ choice.votes|pluralize }}</th>
    </tr>
{% endfor %}
</table>

    {# </ul> #}
<div class="text-center">
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Django Tutorial <br> Author: Kathleen O'Donovan</small>
    </div>
  </footer>

polls/templates/polls/submitted.html
{# load the tag library #}
{% load bootstrap5 %}
{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# display dijango.contrib.messages as bootstrap alerts #}
{% bootstrap_messages %}

<div class="container-fluid">
    <div class="mt-4 p-5 bg-info text-black rounded text-center">
        <h1 >Thank you for submitting a report for poll {{ report_list.0.question_id }} </h1>
        <br>
        <a href = "/polls/">Back to Home</a>
    </div>


    <table class="table table-bordered">
    <thead>
        <tr>
            <th>name</th>
            <th>input</th>
        </tr>
    </thead>
    {% if report_list %}
        {% for report in report_list %}
    <tr>
        <th>{{ report.name}}</th>
        <th>{{ report.input}}</th>
    </tr>
{% endfor %}
    {% endif %}

</table>
</div>
<footer id="sticky-footer" class="fixed-bottom py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Django Tutorial <br> Author: Kathleen O'Donovan</small>
    </div>
  </footer>